### ISSUE TITLE
Create alignment summary page from alignment-nf outputs

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/CeNDR#117]
For new data releases we will attach a summary page associated with alignments. This will join the other tabs you see on CeNDR on [this page](https://elegansvariation.org/data/release/latest):

![image](https://user-images.githubusercontent.com/1536935/75122951-14605a80-569b-11ea-8985-b6f88a178d75.png)

So there will be an additional 'alignment' tab, generated by a markdown report that comes from alignment-nf.

This should include the following elements, displayed in plots and available for download as TSVs:

* [ ] mapping rates
* [ ] discordant / split read rates (on strain level)
* [ ] depth of coverage per strain
* [ ] avg. read length? Other metrics?

This report can be integrated into the alignment-nf. That is probably easier.

**Comment by danielecook** [comment]
@danrlu I will take care of the alignment report page and set it up as the template we will want for the other pipelines: correlation, popgen, and wi-gatk

**Comment by danrlu** [comment]
Done with `cd0886e`
